### ISSUE TITLE
Make a logo for pr-train

### ISSUE THREAD

**Issue by itaditya** [itaditya/pr-train#1]

**Comment by abhayjatindoshi** [comment]
Can you provide more information of what pr-train does to design a logo for it ?

**Comment by itaditya** [comment]
There's a short description [here](https://github.com/itaditya/pr-train#pr-train). I have also added a screenshot of the project in action, so you can get a better idea of what it does.

**Comment by abhayjatindoshi** [comment]
What does train mean in your app name ? 
pr means Pull Requests if I'm not wrong ?

**Comment by itaditya** [comment]
Yeah you are right pr means Pull Request.
Train as in the locomotive. Meant to say one person (engine) has to review these many PRs already (carriage boxes).

So you will assign a new PR (carriage) to the person who has to review least PRs (engine which has to pull least carriages).

**Comment by abhayjatindoshi** [comment]
![image](https://user-images.githubusercontent.com/19318032/66020329-60500e80-e504-11e9-95ab-3625f92d3363.png)

Would this do ?

**Comment by itaditya** [comment]
This is an interesting idea @abhayjatindoshi. Can you make the railway tracks in form of P? That would resemble a PR flow as well, in the sense that you make a branch from master so so you get

I /
I/
I
I

and once you merge the PR, it goes back to master.


I
I\
I \
I /
I/
I
I

Basically, use the railway tracks to form a P in a logo like this
<img width="394" alt="image" src="https://user-images.githubusercontent.com/15871340/66030914-00fff780-e520-11e9-8b82-81126c1c1b8c.png">

**Comment by itaditya** [comment]
Here is a Figma file with this logo, you can make the changes there directly https://www.figma.com/file/hcGuaVVyQxLFRvB1E2ljjy/PR-Train-logo?node-id=0%3A1

**Comment by abhayjatindoshi** [comment]
I think I get you. Let me try what I can do.

**Comment by abhayjatindoshi** [comment]
This should do I guess ?
![image](https://user-images.githubusercontent.com/19318032/66038157-f0a34900-e52e-11e9-8162-a07d2053cab4.png)

**Comment by itaditya** [comment]
Looks great! Just add this symbol in the background design I have made and submit a PR with these files named like this

* logo.svg
* favicon.ico (size 24x24 px)
* logo-128x128.png
* logo-48x48.png
* logo.png (size 180x180 px)

**Comment by abhayjatindoshi** [comment]
Would you need a png if I get you an SVG ? You would be able to scale to any size on html.

**Comment by itaditya** [comment]
png is needed for PWA icons. I think svg is not well supported there

**Comment by abhayjatindoshi** [comment]
Sure then, I'll get those done too.
There seems some problem with github when forking 😖😕 
I've already informed github support. I'll create a PR once they have it resolved.

**Comment by itaditya** [comment]
Cool 👍

**Comment by abhayjatindoshi** [comment]
#8

**Comment by itaditya** [comment]
closed by #4
